import Head from "next/head";

interface IHtmlHeader {
  title: string
}

export const HtmlHeader = ({ title }: IHtmlHeader) => <Head>
  <title>{title}</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🧑‍💻</text></svg>" />
  <script defer src="https://identity.netlify.com/v1/netlify-identity-widget.js" />
</Head>